# -*- coding: utf-8 -*-
"""Command-and-Control Traffic Emulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJkqlssbtTviXuKjuj24zy_UzAEoWmr1
"""

# @title 1. Install Dependencies & Libraries
!pip install scapy flask pandas matplotlib scikit-learn

import logging
import threading
import time
import random
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from flask import Flask, request
from scapy.all import sniff, IP, TCP
from sklearn.ensemble import IsolationForest

# Suppress annoying server logs
log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

print("Dependencies installed. Ready to build the range.")

# @title 2. Define Network Components

# --- CONFIGURATION ---
SERVER_PORT = 5000
SERVER_IP = "127.0.0.1"
DURATION = 40  # Run for 40 seconds to gather enough data for ML
IMPLANT_SLEEP = 2.0  # The malware tries to sleep for 2 seconds
JITTER = 0.5         # +/- 0.5s randomness

# Global list to store traffic data
captured_traffic = []

# --- 1. THE C2 SERVER ---
app = Flask(__name__)

@app.route('/heartbeat', methods=['POST'])
def c2_heartbeat():
    return "COMMAND: SLEEP"

@app.route('/')
@app.route('/news')
@app.route('/images')
def benign_site():
    return "Normal Website Content"

def run_server():
    app.run(port=SERVER_PORT, debug=False, use_reloader=False)

# --- 2. THE IMPLANT (Malicious) ---
def run_implant():
    end_time = time.time() + DURATION
    while time.time() < end_time:
        try:
            # Malware "Phones Home"
            requests.post(f"http://{SERVER_IP}:{SERVER_PORT}/heartbeat", data={"uid": "123"})
        except:
            pass

        # Sleep with Jitter (Target Pattern)
        # It aims for 2.0s but will be between 1.5s and 2.5s
        sleep_time = IMPLANT_SLEEP + random.uniform(-JITTER, JITTER)
        time.sleep(abs(sleep_time))

# --- 3. THE NOISE (Benign User) ---
def run_benign_user():
    end_time = time.time() + DURATION
    endpoints = ["/", "/news", "/images"]

    while time.time() < end_time:
        try:
            target = random.choice(endpoints)
            requests.get(f"http://{SERVER_IP}:{SERVER_PORT}{target}")
        except:
            pass

        # Chaotic sleep (No Pattern)
        # Sometimes fast (0.1s), sometimes slow (4.0s)
        time.sleep(random.uniform(0.1, 4.0))

# --- 4. THE SNIFFER ---
def packet_callback(packet):
    if packet.haslayer(TCP) and packet.haslayer(IP):
        # Capture only traffic GOING to the server
        if packet[TCP].dport == SERVER_PORT:
            captured_traffic.append({"time": packet.time})

def start_sniffing():
    sniff(iface="lo", prn=packet_callback, timeout=DURATION, store=0)

print("Infrastructure defined.")

# @title 3. Run Simulation (Wait 40 Seconds...)
print(f"Starting War Game for {DURATION} seconds...")

# Clear previous data
captured_traffic = []

# Start Server
server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()
time.sleep(2)

# Start Sniffer
sniffer_thread = threading.Thread(target=start_sniffing, daemon=True)
sniffer_thread.start()

# Start Traffic
implant_thread = threading.Thread(target=run_implant)
benign_thread = threading.Thread(target=run_benign_user)

implant_thread.start()
benign_thread.start()

# Wait for finish
implant_thread.join()
benign_thread.join()
sniffer_thread.join()

print(f"Simulation Complete. Captured {len(captured_traffic)} packets.")

# @title 4. Process Data for Analysis
df = pd.DataFrame(captured_traffic)
df = df.sort_values(by='time')

# Calculate Inter-Arrival Time (Delta)
df['delta'] = df['time'].diff()

# Filter noise (remove extremely small deltas like TCP handshakes/ACKs)
# We only care about the gap between actual HTTP Requests
df_clean = df[df['delta'] > 0.1].copy()

# Reset index for clean plotting
df_clean = df_clean.reset_index(drop=True)

print(f"Data Processed. Usable Packets: {len(df_clean)}")
print(df_clean.head())

# @title 5. Machine Learning Detection & Metrics
# Prepare data for Scikit-Learn (Needs 2D array)
X = df_clean['delta'].values.reshape(-1, 1)

# --- 1. TRAIN MODEL (Isolation Forest) ---
# contamination='auto' lets the model decide how much is noise
clf = IsolationForest(contamination='auto', random_state=42)
df_clean['anomaly'] = clf.fit_predict(X)

# Isolate the two groups found by the AI
# In Isolation Forest, -1 is usually the "Anomaly" (The minority group)
# But since C2 is regular, let's group by clusters.
group_1 = df_clean[df_clean['anomaly'] == 1]
group_2 = df_clean[df_clean['anomaly'] == -1]

# --- 2. CALCULATE METRICS ---
# We want to find which group has the LOWER Variance (That's the malware)
var_g1 = group_1['delta'].var()
var_g2 = group_2['delta'].var()

if var_g1 < var_g2:
    malware_detected = group_1
    benign_detected = group_2
    malware_var = var_g1
    benign_var = var_g2
else:
    malware_detected = group_2
    benign_detected = group_1
    malware_var = var_g2
    benign_var = var_g1

print("--- DETECTION METRICS ---")
print(f"Total Packets Analyzed: {len(df_clean)}")
print(f"Suspected Malicious Packets: {len(malware_detected)}")
print(f"Suspected Benign Packets:    {len(benign_detected)}")
print("-" * 30)
print(f"Malware Variance (Jitter):   {malware_var:.5f} (Low = Mechanical)")
print(f"Benign Variance (Chaos):     {benign_var:.5f} (High = Human)")
print(f"Avg Malware Interval:        {malware_detected['delta'].mean():.4f} seconds")

# --- 3. VISUALIZE ---
plt.figure(figsize=(12, 6))

# Plot Benign (Green)
plt.scatter(benign_detected['time'], benign_detected['delta'],
            c='green', label=f'Benign (Var: {benign_var:.2f})', alpha=0.6)

# Plot Malware (Red)
plt.scatter(malware_detected['time'], malware_detected['delta'],
            c='red', label=f'Malware (Var: {malware_var:.2f})', s=60, edgecolors='black')

# Draw the target line
plt.axhline(y=IMPLANT_SLEEP, color='blue', linestyle='--', label=f'Target Interval ({IMPLANT_SLEEP}s)')

plt.title("Machine Learning Classification of C2 Traffic")
plt.xlabel("Timeline (seconds)")
plt.ylabel("Inter-Arrival Time (seconds)")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()